### PR TITLE
New logo for swank #1

### PR DESCRIPTION
**Pull request by hawk28**
Hello, I desgined a logo for Swank. If you like it, i can send a pr. If there is something you want to organize, you can tell me.

Which do you prefer?
lAdd files via upload

New logo for swank 
New logo for swank

### CODE REVIEW

**Comment by LFeh** [comment]
Hi @hawk28, how are you?

What is **Swank**? hahaha

**Comment by hawk28** [comment]
thanks Lfeh :) 
swahnk : Xamarin embeddable image viewer with 360 degree support.

Xamarin is a mobile application development platform.

:D

**Comment by hawk28** [comment]
Hello :)

**Comment by LFeh** [comment]
I yet understand what is it, hahaha.

Is it a new logo?

**Comment by hawk28** [comment]
Yes

**Pull request closed without merging**
